V2XSW-248 Makefile: Fix Yocto Zeus build error
Fix such compile errors:

	| /path/to/yocto/build.imx8qxpc0mek/tmp/work/aarch64-poky-linux/imx-seco-libs/git-r0/recipe-sysroot/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
	|   382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
	|       |    ^~~~~~~
	| cc1: all warnings being treated as errors

Signed-off-by: Stephane Viau <stephane.viau@nxp.com>
(cherry picked from commit bb7bc6bb13112d8fd61d079d9304ccf28ee5e49f)